### ISSUE TITLE
1.11.0：选词栏无故出现

### ISSUE THREAD

**Issue by alx696** [libpinyin/ibus-libpinyin#178]
### 问题描述

系统: Ubuntu 18.04.02

鼠标左键点击任意位置, 选词栏会自动出现在上次光标位置, 选词栏里面的候选项为"1 中华人民共和国 2 中国人民解放军 ...". 如果当前为英文模式, 选词栏一直都在. 如果当前为中文模式, 输入文字后选词栏消失. 再次点击鼠标左键, 问题重复出现.
> Chrome浏览器中Github的Issues编辑中可复现此问题.

**Comment by epico** [comment]
Ubuntu 18.04 自带的 libpinyin 版本是不稳定版本，推荐 libpinyin 2.2.0 或 libpinyin 2.3.0 版本。

**Comment by alx696** [comment]
@epico 我是编译安装的 libpinyin 2.3.0 和 ibus-libpinyin 1.11.0, 而且未开启输入建议功能.

**Comment by epico** [comment]
全新安装高版本的 Ubuntu, 看看能不能复现？

**Comment by epico** [comment]
libpinyin 编译也需要 ./configure --prefix=/usr .

**Comment by alx696** [comment]
@epico 是全新安装的Ubuntu 18.04.2 LTS, 之前因为第一次编译安装没加prefix, 又重新安装了一次系统. 再次编译安装一次成功, 问题是一样的. 值得注意的是好像不需要安装lua, 而且即使安装了make时check还是提示**lua no**. 按照方法见 https://github.com/alx696/share/wiki/Ubuntu#ibus%E6%8B%BC%E9%9F%B3

**Comment by epico** [comment]
推荐打开 lua 脚本支持，默认是打开的。

能否试试更高版本的 Ubuntu 比如 19.04 .

**Comment by alx696** [comment]
@epico lua不清楚什么原因, 安装了, 但是好像检测不到.

19.04不是长期支持版,而且现在很多东西还没支持,暂时没准备用.

**Comment by zbjdonald** [comment]
我也是這個問題 請問解決了馬

**Comment by epico** [comment]
试试 https://launchpad.net/~gunnarhj/+archive/ubuntu/ibus-libpinyin .

这个是第三方的 repo.

**Comment by ping-wu** [comment]
Please see the following thread for installing ibus-libpinyin 1.11 in Ubuntu 18.04LTS:

https://forum.ubuntu.org.cn/viewtopic.php?f=8&t=489689&start=20

(Because of the forum is currently not very stable, I am pasting the content below)

Re: 唉！输入法又坏了！
#21 帖子  由 Ping-Wu » 2019-06-04 16:19
百草谷居士 写了： ↑
测试有什么具体要求吗？
先启动 “软件和更新”（Software & Updates）app --》 “开发者选项”（Developers Option) --》“提前释放出的更新”（Pre-Released Updates)：
Screenshot from 2019-06-03 20-13-35.jpg
然后执行下列指令：
代码： 全选

sudo apt update
代码： 全选

sudo apt install ibus-libpinyin libpinyin-data libpinyin13
装完以后，确认 ibus-libpinyin 是最新版的 1.11：
代码： 全选

dpkg-query -W ibus-libpinyin libpinyin-data libpinyin13
结果应该是：

ibus-libpinyin 1.11.0-1ubuntu0.18.04.1
libpinyin-data:amd64 2.2.2-1~ubuntu18.04.1
libpinyin13:amd64 2.2.2-1~ubuntu18.04.1

一切OK以后，再启动 “软件和更新”（Software & Updates）app --》把 “提前释放出的更新”（Pre-Released Updates) 勾掉。
百草谷居士 写了： ↑
虽然对不支持拼音直接输入特殊符号很不满意，但测试还是可以参加的。
个体户用什么输入法，自己爽就好了。不过如果在较有制度的公司做事的话，像我们就绝对不会让使用者乱动系统，基本上没有选择自己习惯输入法的自由。目前几个较为企业界接受的中文输入法就只有 ibus-libpinyin。如我前面提到的，最少对我个人而言，不管满不满意，总要帮忙让它好用一点。

**Comment by epico** [comment]
Fixed in libpinyin 2.3.0.
