### ISSUE TITLE
Increase the size of the proposed characters.

### ISSUE THREAD

**Issue by rere-rere** [libpinyin/ibus-libpinyin#240]
Hello,

I would like to know if there is a way to increase the size of the proposed characters.
Indeed, I have some difficulties to see characters and I wanted to know if this option is available. 
But, I searched and didn't find this one in the parameters menu of the application.

> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.4 LTS
> Release:	18.04
> Codename:	bionic

Thank you in advance for your help.
Best regards

**Comment by epico** [comment]
https://extensions.gnome.org/extension/1121/ibus-font-setting/

**Comment by seedship** [comment]
Inside ibus preferences (ibus-setup from terminal), under general, I can tick 'Use custom font' and make the font bigger

**Comment by tuberry** [comment]
@seedship 试试这个新上架的 https://extensions.gnome.org/extension/2820/ibus-tweaker/

**Comment by seedship** [comment]
@tuberry 谢谢，但我不用gnome 我用的xfce4 :( 
![image](https://user-images.githubusercontent.com/885667/81550784-04464600-9381-11ea-94a3-f39b9175009c.png)
我从ibus preferences能改 字的大小 真的满方便

**Comment by Lilalas** [comment]
I tried to use the method suggested by @seedship, but unfortunately it has absolutely no effect (even after restart).

Also I’m confused because the list of input methods in `ibus-setup` only displays the default keyboard, although `ibus-libpinyin` is definitely installed and IBus is activated as the input method system under language settings.

![IBus Preferences](https://user-images.githubusercontent.com/10713547/106339050-bae2b180-6295-11eb-8414-1e87476df355.png)

I don’t understand what’s happening. Shall I open a new issue?

**Comment by seedship** [comment]
@Lilalas maybe try the gnome extensions tweak mentioned in the previous comments? My experience with these things is that DEs often play a bigger role than one would think.

I am using LightDM and XFCE, which is quite different than the standard Ubuntu setup, which might make a difference.

Its weird that you don't have Chinese in the list of languages though. Can you add it?

**Comment by Lilalas** [comment]
Yes, the extension posted above does indeed work for me, thank you for suggesting it! After installing the extension, the dialogue in `ibus-setup` works as intended. So that solves the issue for me — except the fact that I would have _expected_ this option work regardless of any installed extension, since it doesn’t say so in the UI.

---

> Its weird that you don't have Chinese in the list of languages though. Can you add it?

Yes, I can add all my installed keyboards to that list, but apparently it doesn’t change anything. I don’t need to add it there for the font setting to take effect. I’m still confused, but whatever, everything is working.

**Comment by epico** [comment]
For GNOME desktop, please use gnome-control-center to setup input methods.
