### ISSUE TITLE
ibus-libpinyin installation issue on Ubuntu Linux

### ISSUE THREAD

**Issue by primohan01** [libpinyin/ibus-libpinyin#63]
Hi,
 I have installed ibus-libpinyin-master for pinyin input (Chinese language ) and found it is required ibus-1.5.11 ,So again I started downloading ibus-1.5.11 but it was required other installation packages like gtk-doc-1.25 but while configuring I am getting below error.
 Error:
 Could not find DocBook XSL sttylesheets in XML catalog.
 So Could you suggest what is the best way to install ibus-1.5.11 without installing the dependency so that below steps can be executed successfully.
 Build & Install libpinyin
 Download libpinyin source from SourceForge
  $ tar zxvf libpinyin-xx.tar.gz
 $ cd libpinyin-xx
 $ ./autogen.sh --prefix=/usr
 $ make
 $ sudo make install
 
 As per my requirement I need to build and compile libpinyin on windows and yocto platform as well.
 Apart from this do u have any packages which support the all the 18 languages.
 ### Your environment
 Windows, Linux, Yocto
 
 ### Steps to reproduce
 After installing the package through below step ./autogen.sh 
 --prefix=/usr I am getting error package requirement were not met: ( 
 ibus-1.0 >=1.5.11)
 
 ### Expected behaviour
 Installation should happen without any dependency.
 
 ### Actual behaviour
 Error is coming
  ### Log
NA

**Comment by epico** [comment]
I update ibus-libpinyin to use ibus 1.5.11 to use ibus_keyval_name function,
in order to drop gdk-3.0 depends.

URL: https://github.com/libpinyin/ibus-libpinyin/commit/ac63a9737c418d562f971c07d697ae0fb3e9b7a2

Maybe you could try to revert the above patch, then use ibus 1.5.0 to check whether it compiles.

Sorry, I don't understand the 18 languages support.

If I remember correctly, libpinyin doesn't contains any string translations.

**Comment by primohan01** [comment]
Hi  ,

Thanks for your mail.  I mean to say is there any possibility to have pinyin to English or English  (or other language) to pinyin translation facility with
This plugin.

Regards,
Mohan

**Comment by epico** [comment]
I think it is not supported in libpinyin code.

**Comment by epico** [comment]
close issue.
