### ISSUE TITLE
Strange Behaviour on Firefox & Lastpass

### ISSUE THREAD

**Issue by ghost** [libpinyin/ibus-libpinyin#81]
I'm running Arch with Gnome and have ibus-libpinyin installed. 

If I'm in Firefox and try to input my password, it will flash and I cannot input anything. If I remove Pinyin from Input Sources, the bug will stop. 

Thank you~

**Comment by epico** [comment]
Actually ibus-libpinyin is named "Intelligent Pinyin" now.
Could you test it with "Intelligent Pinyin" ?

**Comment by T-ii** [comment]
I'm not sure what you mean, I installed [this package.](https://www.archlinux.org/packages/community/x86_64/ibus-libpinyin/)

**Comment by epico** [comment]
I mean to add "Intelligent Pinyin" to Input Sources.

**Comment by T-ii** [comment]
Yes, it is already added to my Input Sources [seen here](http://imgur.com/a/a9Xb1)

The bug still happens.

**Comment by epico** [comment]
Okay, I will have a look.

**Comment by T-ii** [comment]
If you need any more information, I will help.

**Comment by epico** [comment]
Sorry, I just installed Arch Linux, but I can't re-produce the bug.

Could you provides more information, such as web site URL, etc?

**Comment by T-ii** [comment]
I'm running Arch with Gnome. It's on any website with Firefox and Lastpass installed. 

When I have Intelligent Pinyin enabled, once I try to open the Lastpass menu to sign in, it closes and won't let me type anything. I also notice in the status bar, the language options flash and reappear.

**Comment by epico** [comment]
Maybe you could contact lastpass developer I think.

**Comment by ganloo** [comment]
I run into this issue only under xorg. When it's in wayland (gnome), it's OK. I don't think it's an issue of Lastpass, since popover (login-in) menus  of firefox extensions will disappear whenever the focus is changed into Password textbox, the normal textbox works with ibus libpinyin, and this issue occurs on not only libpinyin but all ibus input modules (saying ibus-rime or ibus-sunpinyin).

**Comment by RubyTuesdayDONO** [comment]
i'm experiencing the same issue with 1Password's popup dialog in Firefox. the effects can be observed elsewhere, in password fields on web pages. i suspect it may have more to do with some interaction between Intelligent Pinyin and password fields in Firefox, because the "flashing" (continuously losing and re-gaining input focus) happens in web page password fields even when 1Password and LastPass extensions are disabled. unfortunately, this makes Intelligent Pinyin practically unusable, since i would have to disable it every time i need to type a web password or unlock my password manager.

Linux 3.10.0-1062.12.1.el7.x86_64
RHEL 7.7-9
GNOME 3.28.2
Firefox 68.6.0esr (64-bit)

**Comment by epico** [comment]
Could you report this issue to Firefox in Red Hat Bugzilla?
